# Рабочая тетрадь №3 Меджидов Магомедпаша Султановчи БФБО-01-22

# Задание 1.3.1 


Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [33]:
import numpy as np

x = np.zeros((8,8),dtype=int)
x[1::2,::2]= 1
x[::2, 1::2]= 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Задание 1.3.2



Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange

In [43]:
import numpy as np
x = np.zeros((5,5),dtype = int) + np.arange(5)
print(x)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# Задание 1.3.3
Создать массив 3x3x3 со случайными значениями



In [59]:
import numpy as np

# mass = np.empty((3,3),dtype = int)
mass = np.random.random((3,3,3))
print(mass)

[[[8.41654447e-01 4.32168063e-01 8.57097800e-01]
  [6.34046323e-01 5.95915067e-04 9.75389146e-01]
  [9.62227951e-01 9.27890239e-01 2.69043196e-01]]

 [[1.33272855e-01 4.24537601e-01 6.04702561e-02]
  [3.35396578e-01 7.75494226e-01 5.11869398e-01]
  [4.65228051e-02 7.02546321e-01 2.17541971e-01]]

 [[7.64345424e-01 5.29704020e-01 1.75402745e-01]
  [8.34568008e-01 4.21790781e-01 6.43570518e-01]
  [6.23299668e-01 7.03564276e-01 9.68510473e-01]]]


# Задание 1.3.4
Создать матрицу с 0 внутри, и 1 на границах

In [91]:
import numpy as np

mass = np.zeros((5,6),dtype = int)
mass[::, 0] = 1
mass[::, -1] = 1
print(mass)

[[1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]]


# Задание 1.3.5
Создайте массив и отсортируйте его по убыванию


In [109]:
import numpy as np

# x = np.zeros((5,5),dtype = int) + np.arange(5)
x = np.array([-1,3,532,1,3,123,2131,41242,12421])
print(np.sort(x)[::-1])


[41242 12421  2131   532   123     3     3     1    -1]


# Задание 1.3.6
Создайте матрицу, выведите ее форму, размер и размерность.



In [1]:
import numpy as np

x = np.zeros((10,10),dtype = int)
print(x)
print('Форма: {}\nРазмерность: {}\nРазмер: {}'.format(x.shape,x.ndim,x.size))

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Форма: (10, 10)
Размерность: 2
Размер: 100


# Задание 2.3.1
Найдите евклидово расстояние между двумя Series (точками) a и b,
не используя встроенную формулу.

In [10]:
from math import *
import numpy as np

distance = np.sqrt(sum(pow(a-b, 2) for a, b in zip((0,0), (3,3))))
print(distance)

4.242640687119285


# Задание 2.3.2
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данный можно найти
здесь: https://github.com/akmand/datasets)


In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/akmand/datasets/main/adult.csv"


dataframe = pd.read_csv(url)

dataframe.head(5)

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K

# Задание 2.3.3
Проделайте с получившемся из предыдущего задания фреймом
данных те же действия, что и в примерах 2.2.5-2.2.7


In [3]:
import pandas as pd


url = "https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv"


df = pd.read_csv(url)
anls = df.head(2)
data_loc = df.iloc[1:4]

new_df = df[
    (df['count'] > 17000)
    ].head(5)

print(f"2.2.5 - {anls}\n"
      f"2.2.6 - {data_loc}\n"
      f"2.2.7 - {new_df}")

2.2.5 -    year    name gender  count
0  2000   Emily      F  25956
1  2000  Hannah      F  23082
2.2.6 -    year     name gender  count
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
2.2.7 -    year     name gender  count
0  2000    Emily      F  25956
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702


# Задание 3.3.2
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.


In [3]:
import pandas as pd
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)
scaler_minmax = preprocessing.MinMaxScaler()
scaler_z = preprocessing.StandardScaler()

df['sepal_length_cm'] = scaler_minmax.fit_transform(df[['sepal_length_cm']])
df['sepal_width_cm'] = scaler_z.fit_transform(df[['sepal_width_cm']])
print(df)


     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 